name: Validar Script Shell

on:
  push:
    branches:
      - main  # Se ejecuta al hacer push a la rama main

jobs:
  shellcheck:
    runs-on: ubuntu-latest  # Usa una m치quina virtual con Ubuntu

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3  # Esta acci칩n descarga tu c칩digo

      - name: Instalar ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
        # Instala ShellCheck en la m치quina virtual

      - name: Ejecutar ShellCheck en script.sh
        run: shellcheck script.sh
        # Ejecuta shellcheck en tu archivo script.sh
